version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/lazylms
    binary: lazylms
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: Rugz007
    name: lazylms
  prerelease: auto

brews:
  - repository:
      owner: Rugz007
      name: homebrew-tap
    homepage: https://github.com/Rugz007/lazylms
    description: "A minimal TUI client for LM Studio"
    license: MIT
    test: |
      system "#{bin}/lazylms", "--help"
